services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: wb_app
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - wb_network

  nginx:
    image: nginx:stable-alpine
    container_name: wb_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - wb_network

  mysql:
    image: mysql:8.0
    container_name: wb_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wb_inventory
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - wb_mysql_data:/var/lib/mysql
    networks:
      - wb_network

networks:
  wb_network:
    driver: bridge

volumes:
  wb_mysql_data: